AWSTemplateFormatVersion: "2010-09-09"
Description: CF template for deploying single-page static serverless site
Parameters:
    SiteFQDN:
        Type: String
        Default: samplewebpage.josh-rosenberg.com
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref SiteFQDN
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
        DeletionPolicy: Delete
