AWSTemplateFormatVersion: "2010-09-09"
Description: CF template for deploying single-page static serverless site
Parameters:
    SiteFQDN:
        Type: String
        Default: samplewebpage.josh-rosenberg.com
Resources:
    MyBucket:
        # Bucket for the website.
        #
        # We're not using WebsiteConfiguration (s3 static website hosting)
        # because of a lack of https support.
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref SiteFQDN
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                IgnorePublicAcls: true
                BlockPublicPolicy: false
                RestrictPublicBuckets: false
        DeletionPolicy: Delete
    MyBucketPolicy:
        # Public access policy for the bucket
        Type: AWS::S3::BucketPolicy
        Properties:
            PolicyDocument:
                Id: MyPolicy
                Version: 2012-10-17
                Statement:
                    - Sid: PublicReadForGetBucketObjects
                      Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Join
                          - ''
                          - - 'arn:aws:s3:::'
                            - !Ref MyBucket
                            - /*
            Bucket: !Ref MyBucket
